spring:
  application:
    name: api-message
  redis:
    database: 1
    host: travelproject.top
    port: 6379
  datasource:
    url: jdbc:mysql://www.travelproject.top:3306/travel_message?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
# 邮箱发送配置
  mail:
    host: smtp.qq.com
    username: 1171459431@qq.com
    password: xywecghmoytegidb #邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
 mapperLocations: classpath*:/mapper/*.xml
 typeAliasesPackage: com.travel.api.beans
server:
  port: 10001
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
     defaultZone: http://localhost:8080/eureka
logging:
  config: classpath:logback.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 聚合数据
JUHE_APPKEY: f05cee7350dc82e78d7582b768a2e3fb
JUHE_OPENID: JH798cf8af342604e0c7f6aa14b0060c56
JUHE_SMS_TEMPLATE_ID: 96336 #模板id


