spring:
  application:
    name: api-information
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/travel_information
server:
  port: 10003
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
     defaultZone: http://localhost:8080/eureka
logging:
  config: classpath:logback.xml
